title: PatchRequest Blog
email: blog@patchrequest.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a infosec/tech blog from me(PatchRequest) about what i am interested in.

markdown: kramdown
url: "https://patchrequest.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""

# for atom feed
author:
  name: Sharad Raj Singh Maurya
  email: dev_sharad@outlook.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
